colorScheme = "neon"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts", "pages"]

[homepage]
layout = "profile"
image = "images/csc-logo.png"

[author]
name = "UCLH-CSC"

[header]
layout = "fixed"
logo = "images/csc-logo.png"
showTitle = false

[article]
showDate = false
showAuthor = false
showViews = false
showLikes = false
showReadingTime = false
showWordCount = false