colorScheme = "blowfish"

enableSearch = true
enableCodeCopy = true

mainSections = ["posts", "pages"]

[homepage]
layout = "background"
image = "images/csc-logo.png"
cardView = true

[author]
name = "UCLH-CSC"

[header]
layout = "fixed"
logo = "images/csc-logo.png"
showTitle = false

[article]
showDate = false
showAuthor = false
showViews = false
showLikes = false
showReadingTime = false
showWordCount = false

[list]
showCards = true
groupByYear = false
cardView = true

[customCSS]
  enable = true