baseURL = "https://<UCLH-CSC>.github.io/csc-website/"
languageCode = "en-gb"
title = "CSC UCLH"
theme = "ananke"

[params]
  description = "Clinical Scientific Computing at University College London Hospital"
  show_reading_time = false